name: data
on:
  schedule:
    - cron: 5 8 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./src/data/postprocess.js

jobs:
  pre_job:

    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/data
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
 
  dataCollection1:
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      # postprocessing files should be in .js or .ts and be in the workflows directory
      # opening with flat config will remove comments
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: FetchData1
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/global_data/vaccine_data_global.csv
          downloaded_filename: ./src/data/vaccineDailyReport.csv

      # Remove Get current date and everything below mkdir to open with flat config to add new sources
      # or to add a postprocessing file
      # postprocessing files should be in .js or .ts and be in the workflows directory
      # opening with flat config will remove comments
      - name: Get yesterday's date
        id: date
        run: echo "::set-output name=date::$(date -d 'yesterday' +'%m-%d-%Y')"
      - run: echo ${{ steps.date.outputs.date }}

      - name: Fetch data 2
        uses: githubocto/flat@v3
        with:       
          http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/${{ steps.date.outputs.date }}.csv
          # http_url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-29-2022.csv
          downloaded_filename: ./src/data/jhu.csv
  postprocess:
    needs: dataCollection1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/data
    steps: 
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
      - name: process files
        run: deno run -A --unstable postprocess.js # A postprocessing javascript or typescript file written with Deno
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

